export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const CHOOSE_THEME = 'CHOOSE_THEME';
export const CHOOSE_COLOR = 'CHOOSE_COLOR';
export const SHOW_COLORS ='SHOW_COLORS'
export const CHOOSE_COLOR_THEME= 'CHOOSE_COLOR_THEME'